sudo: required
language: go

services:
  - docker

env:
  global:
    - IMAGE_NAME=tasks:this

before_install:
  - brew install hadolint
  - hadolint Dockerfile
install:
  - hooks/build

script:
  - docker images
  - hooks/test
